import os
import sys
import time

from pathlib import Path
from contextlib import contextmanager

s=sys.argv.pop(0)

m=0
m|=1<<0
m|=1<<1

while sys.argv:
    if sys.argv[0] in ("-h","--help"):
        print(f"{s} [-a] [-t] [PATH]")
        print("PATH - must be a path to data directory or similar")
        print("-a   - bundle only asset")
        print("-t   - bundle only translation")
        print("-f   - force deletion of non-autogenerated files")
        print("-s   - mostly silent")
        sys.exit(1)
    elif sys.argv[0] == "-a":
        m=0b1+m&1<<2
    elif sys.argv[0] == "-t":
        m=0b10+m&1<<2
    elif sys.argv[0] == "-s":
        m|=1<<2
    elif sys.argv[0] == "-f":
        m|=1<<3
        print("I really hope you know what you are doing by forcing me")
    else:
        if m&1<<2==0:
            print("Assuming {} is the path".format(sys.argv[0]))
            time.sleep(1)
            print("If not respond with ctrl+c in the next five seconds.")
            try:time.sleep(5)
            except KeyboardInterrupt:
                print("Alright then change the input and try again.")
                time.sleep(0.2)
                print("Good bye")
                sys.exit(1)
        else:
            print("Using: {}".format(sys.argv[0]))
        break
    sys.argv.pop(0)

tb=0
try:walk_dir = Path(sys.argv[0] or os.getcwd())
except:
    walk_dir = Path(os.getcwd())
    if m&1<<2==0:
        print("That's bad.")
        tb|=1
        time.sleep(2)
        print("You did not provide a directory.")
        time.sleep(1)
        print("Anyway I would try with {}.".format(walk_dir))
        time.sleep(1)
        print("If not respond with ctrl+c in the next five seconds.")
        try:time.sleep(5)
        except KeyboardInterrupt:
            print("Alright then change the input and try again.")
            time.sleep(0.2)
            print("Good bye")
            sys.exit(1)
    else:
        print("Using: {}".format(walk_dir))

if m&1<<2==0: print("\n")

if "data" in [i.name for i in walk_dir.iterdir()]:
    rootdir=walk_dir
else:
    print("Ehm I did not found the data directory so easily.")
    print("I try to search for it.")
    def rec(wd):
        a=wd.iterdir()
        if sum(1 for _ in a)==1:
            if a=="data":
                return wd
            else:
                return rec(wd/a[0])
        else:
            return None
    a=rec(walk_dir)
    def rec2(wd):
        a=wd.name
        if a=="data":return wd.parent
        elif wd.parent.is_mount():return None
        else: return rec2(wd.parent)
    b=rec2(walk_dir)
    if a!=None and b!=None:
        if m&1<<2==0:
            try:
                print("Oh no!")
                time.sleep(0.5)
                print("The filetree is ambigous")
                time.sleep(0.2)
                print("I found a data directory in {} and in {}".format(a,b))
                ai=len(a.relative_to(walk_dir, walk_up=True).parts)
                bi=len(b.relative_to(walk_dir, walk_up=True).parts)
                if ai!=bi:
                    print("I will not decide which one is right but ",end="")
                    time.sleep(0.5)
                    sys.stdout.write(".")
                    time.sleep(0.5)
                    sys.stdout.write(".")
                    time.sleep(0.5)
                    sys.stdout.write(".")
                    sys.stdout.write("\b\b\b")
                    print("I guess it is the {}.".format("first" if ai<bi else "second"))
                else:
                    print("A very very complex problem, but not for me ;-)")
                time.sleep(0.2)
                print("Please solve it or just give me the path to the correct directory.")
            except KeyboardInterrupt:
                print("\nOh you have timing problems?")
                time.sleep(0.5)
                print("Then go.")
                time.sleep(0.5)
                print("Consider using -s if I talk to much.")
        else:
            print("Faulty directory")
        time.sleep(0.2)
        print("Good bye")
        sys.exit(1)
    if a==b==None:
        if m&1<<2==0:
            try:
                print("Did I say before it was bad?")
                time.sleep(2)
                if tb&1 == 1:
                    print("Well, now we have a real badass problem.")
                    time.sleep(2)
                    print("Yes. I did not found a valid directory either.")
                else:
                    print("No? Okay. That's bad.")
                    print("Either I am blind or there is no data directory above or below which I can use.")
                time.sleep(1)
                print("I'm begging you, gimme the right directory. Until then...")
            except KeyboardInterrupt:
                print("\nYeah just go and leave me with this shi**y problem")
                print("But dare not to come to me with another faulty directory!")
        else:
            print("Faulty directory")
        time.sleep(0.2)
        print("Good bye")
        sys.exit(1)
    rootdir= a or b
    print("Heh. Found it!")

print("I may have to do some preparations\n")

(walk_dir/"data"/"config"/"export"/"main"/"asset").mkdir(exist_ok=True,parents=True)
if (walk_dir/"data"/"config"/"export"/"main"/"asset"/"assets.xml").exists():
    print("Assets are already there.")
    j=True
    with (walk_dir/"data"/"config"/"export"/"main"/"asset"/"assets.xml").open() as fd:
        j=fd.readline().strip()!="<!--autogenerated DO NOT CHANGE-->"
    if j:
        if m&0b1000==0:
            print("I refuse to go on as it does not seem to be autogenerated.")   
            sys.exit(1)
        else:
            print("I hope you know what you are doing")
    else:
        print("Seems to be autogenerated")
    print("Removing assets.xml")
    (walk_dir/"data"/"config"/"export"/"main"/"asset"/"assets.xml").unlink(missing_ok=True)
    print("")

(walk_dir/"data"/"config"/"gui").mkdir(exist_ok=True, parents=True)

if m&1<<1==1<<1:
    for root, dirs, files in (walk_dir/"data"/"config"/"gui").walk(top_down=False):
        for name in files:
            if name.startswith("texts_") and name.endswith(".xml"):
                print(f"{name} is already there")
                j=True
                with (root / name).open() as fd:
                    j=fd.readline().strip()!="<!--autogenerated DO NOT CHANGE-->"
                if j:
                    if m&0b1000==0:
                        print("I refuse to go on as it does not seem to be autogenerated.")
                        sys.exit(1)
                    else:
                        print("I hope you know what you are doing")
                else:
                    print("Seems to be autogenerated")
                print("Removing "+name)
                (root / name).unlink()
                print("")

@contextmanager
def langfiles():
    class c(object):
        fs={}
        def open(s, f):
            if not isinstance(f,Path):
                if f.find("/")+f.find("\\")<0:f=(walk_dir/"data"/"config"/"gui"/f)
            if f in s.fs:return s.fs[f]
            if f.exists():
                if m&0b100==0:
                    print("Hm that's odd...")
                    time.sleep(1)
                    print("The file {} should not exist there but nevertheless it is there.".format(f))
                if m&0b1000!=0:
                    print("Ignoring {}".format(f if m&0b100 else "it."))
                    f.unlink()
                else:
                    print("I better stop.")
                    time.sleep(0.1)
                    print("Good bye")
                    sys.exit(1)
            fd=f.open("a")
            fd.write("<!--autogenerated DO NOT CHANGE-->\n")
            fd.write("<!--You will lose data if this preamble is in this file and you changed something here-->\n")
            fd.write("<ModOps>")
            s.fs[f] = fd
            return fd
        def __getitem__(self,k):
            if k in self.fs:return self.fs[k]
            else: return self.open(k)
        def __setitem__(s,k,v):
            pass
        def close(s):
            for v in s.fs.values():
                try:
                    v.write("</ModOps>")
                    v.close()
                except Exception as e:
                    print(e)
    o=c()
    try:
        yield o
    finally:
        o.close()

if m&1:print("Bundling Assets")
if m&2:print("Building Translations")


print("Alright let's")

with (walk_dir/"data"/"config"/"export"/"main"/"asset"/"assets.xml").open("a") as g, langfiles() as tl:
    g.write("<!--autogenerated DO NOT CHANGE-->\n")
    g.write("<!--You will lose data if this preamble is in this file and you changed something here-->\n")
    g.write("<ModOps>\n")
    for root, subdirs, files in rootdir.walk():
        if len(root.parts)>len(walk_dir.parts):
            x=root.relative_to(walk_dir).parts
        else:
            x=walk_dir.relative_to(root).parts
        if walk_dir!=root and len(x)>1 and x[1]=="config": continue
        for file in files:
            f = root/file
            if file=="asset.xml" and m&1==1:
                print(f"Asset found: {f}")
                with f.open() as fd:
                    g.write("\n<!-- {} -->\n".format(f))
                    g.write(fd.read().replace("<ModOps>","").replace("</ModOps>","").strip())
                    g.write("\n")
            if file.startswith("texts_") and file.endswith(".xml") and m&1<<1==1<<1:
                print("Language found: {}".format(f))
                z=tl[file]
                with f.open() as fd:
                    z.write("\n<!-- {} -->\n".format(f))
                    z.write(fd.read().replace("<ModOps>","").replace("</ModOps>","").strip())
                    z.write("\n")
    g.write("</ModOps>\n")

print("\nI am done.")
